version: "3"
services:
  foundry:
    env_file: ./env.d/foundry
    image: felddy/foundryvtt:release
    init: true
    volumes:
      - "./foundry/data:/data"
      - "./foundry/home:/home/foundry"
    ports:
      - 30000:30000
    restart: unless-stopped
  cloudflared:
    env_file: ./env.d/cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: unless-stopped
