version: "3"
services:
  foundry:
    env_file: ./env.d/foundry
    image: "felddy/foundryvtt:${VERSION}"
    init: true
    volumes:
    # you may want to change this to wherever you want all of 
    # the files and data for this foundry server to live.
    # 
    # example
    # /media/adventure-game/data:/data
    #
    # otherwise it will default to a directory named foundry-data in this directory, which is also fine.
      - "./foundry-data:/data"
    restart: unless-stopped
  cloudflared:
    env_file: ./env.d/cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: unless-stopped
