version: "3"
services:
  foundry:
    env_file: ./env.d/foundry
    image: felddy/foundryvtt:release
    init: true
    volumes:
    # you will want to change this to wherever you want all of 
    # the files and data for this foundry server to live.
    # 
    # i.e.
    # 
    # /path/to/a/folder/for/this:/data
      - "./foundry/data:/data"
    restart: unless-stopped
  cloudflared:
    env_file: ./env.d/cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: unless-stopped
